apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: mlops-pipeline-
  annotations: {pipelines.kubeflow.org/kfp_sdk_version: 1.8.22, pipelines.kubeflow.org/pipeline_compilation_time: '2025-08-20T17:26:14.362683',
    pipelines.kubeflow.org/pipeline_spec: '{"description": "This is a kubeflow pipeline",
      "name": "mlops-pipeline"}'}
  labels: {pipelines.kubeflow.org/kfp_sdk_version: 1.8.22}
spec:
  entrypoint: mlops-pipeline
  templates:
  - name: data-processing
    container:
      command: [python, src/data_processing.py]
      image: sanjayn96/colorectal-cancer:latest
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.22
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
  - name: mlops-pipeline
    dag:
      tasks:
      - {name: data-processing, template: data-processing}
      - {name: model-training, template: model-training}
  - name: model-training
    container:
      command: [python, src/model_training.py]
      image: sanjayn96/colorectal-cancer:latest
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.22
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
  arguments:
    parameters: []
  serviceAccountName: pipeline-runner
